FEATURE_NAMES = [
    "url_length",
    "hostname_length",
    "path_length",
    "query_length",
    "fragment_length",
    "num_dots",
    "num_hyphens",
    "num_underscores",
    "num_slashes",
    "num_question_marks",
    "num_equals",
    "num_ampersands",
    "num_percent",
    "num_digits",
    "digit_ratio",
    "num_letters",
    "letter_ratio",
    "has_https",
    "has_http",
    "has_ip",
    "has_at",
    "has_double_slash_redirect",
    "has_punycode",
    "has_port",
    "subdomain_count",
    "tld_length",
    "registered_domain_length",
    "path_depth",
    "num_query_params",
    "sensitive_keyword_count",
    "brand_in_subdomain",
    "brand_in_path",
    "brand_in_hostname_not_etld",
    "shortest_brand_distance",
    "is_shortener",
    "hostname_entropy",
    "url_entropy",
    "has_hex_escape",
    "vowel_ratio_hostname",
    "consecutive_digits",
    "max_label_length",
    "num_labels",
    "has_www",
    "has_credential_in_userinfo",
]

BRANDS = [
    {"name": "PayPal", "tokens": ["paypal"], "domains": ["paypal.com", "paypal.me", "paypalobjects.com"]},
    {"name": "Apple", "tokens": ["apple", "icloud", "appstore"], "domains": ["apple.com", "icloud.com", "appleid.com", "me.com", "mac.com"]},
    {"name": "Google", "tokens": ["google", "gmail", "youtube"], "domains": ["google.com", "gmail.com", "youtube.com", "youtu.be", "googleapis.com"]},
    {"name": "Microsoft", "tokens": ["microsoft", "outlook", "office365", "onedrive", "hotmail", "live"], "domains": ["microsoft.com", "microsoftonline.com", "live.com", "outlook.com", "office.com", "hotmail.com"]},
    {"name": "Amazon", "tokens": ["amazon", "aws", "kindle"], "domains": ["amazon.com", "amazon.co.uk", "amazonaws.com"]},
    {"name": "Facebook", "tokens": ["facebook", "instagram", "whatsapp"], "domains": ["facebook.com", "fb.com", "instagram.com", "whatsapp.com"]},
    {"name": "Netflix", "tokens": ["netflix"], "domains": ["netflix.com"]},
    {"name": "eBay", "tokens": ["ebay"], "domains": ["ebay.com"]},
    {"name": "Bank of America", "tokens": ["bankofamerica", "bofa"], "domains": ["bankofamerica.com", "bofa.com"]},
    {"name": "Chase", "tokens": ["chase", "jpmorgan"], "domains": ["chase.com", "jpmorgan.com", "jpmorganchase.com"]},
    {"name": "Wells Fargo", "tokens": ["wellsfargo"], "domains": ["wellsfargo.com"]},
    {"name": "Citi", "tokens": ["citibank", "citi"], "domains": ["citi.com", "citibank.com"]},
    {"name": "American Express", "tokens": ["americanexpress", "amex"], "domains": ["americanexpress.com", "amex.com"]},
    {"name": "USPS", "tokens": ["usps"], "domains": ["usps.com", "usps.gov"]},
    {"name": "UPS", "tokens": ["ups"], "domains": ["ups.com"]},
    {"name": "FedEx", "tokens": ["fedex"], "domains": ["fedex.com"]},
    {"name": "DHL", "tokens": ["dhl"], "domains": ["dhl.com"]},
    {"name": "Adobe", "tokens": ["adobe"], "domains": ["adobe.com", "adobelogin.com"]},
    {"name": "Dropbox", "tokens": ["dropbox"], "domains": ["dropbox.com"]},
    {"name": "LinkedIn", "tokens": ["linkedin"], "domains": ["linkedin.com"]},
    {"name": "Binance", "tokens": ["binance"], "domains": ["binance.com"]},
    {"name": "Coinbase", "tokens": ["coinbase"], "domains": ["coinbase.com"]},
    {"name": "Steam", "tokens": ["steampowered", "steamcommunity"], "domains": ["steampowered.com", "steamcommunity.com"]},
    {"name": "IRS", "tokens": ["irs"], "domains": ["irs.gov"]},
    {"name": "DocuSign", "tokens": ["docusign"], "domains": ["docusign.com", "docusign.net"]},
    {"name": "GitHub", "tokens": ["github"], "domains": ["github.com", "githubusercontent.com"]},
    {"name": "Stripe", "tokens": ["stripe"], "domains": ["stripe.com"]},
    {"name": "Walmart", "tokens": ["walmart"], "domains": ["walmart.com"]},
    {"name": "HSBC", "tokens": ["hsbc"], "domains": ["hsbc.com", "hsbc.co.uk"]},
]

CREDENTIAL_KEYWORDS = [
    "login", "signin", "sign-in", "log-in", "secure", "account", "update",
    "verify", "verification", "confirm", "password", "passwd", "credential",
    "wallet", "billing", "invoice", "recover", "unlock", "limited", "suspend", "urgent",
]

SHORTENERS = {
    "bit.ly", "bitly.com", "tinyurl.com", "t.co", "ow.ly", "buff.ly", "shorturl.at",
    "is.gd", "cutt.ly", "rebrand.ly", "tiny.cc", "rb.gy", "adf.ly", "j.mp", "lnkd.in",
}

MULTI_PART_TLDS = {
    "co.uk", "ac.uk", "gov.uk", "org.uk", "com.au", "net.au", "org.au", "edu.au",
    "gov.au", "co.nz", "co.jp", "co.kr", "co.za", "com.br", "com.mx", "co.in",
    "com.cn", "com.tw", "com.hk", "com.sg", "com.my", "co.id", "com.ar", "com.tr",
    "github.io", "gitlab.io", "herokuapp.com", "netlify.app", "azurewebsites.net",
    "s3.amazonaws.com", "blob.core.windows.net", "web.app", "firebaseapp.com",
    "appspot.com", "pages.dev", "workers.dev", "cloudfront.net",
}
